// JSON Object

var json = {
	"part1": {
		"groups": ["Group:", "Engine"],
		"fullname": ["Full Name:", "Jonell Colon"],
		"phone": ["Phone:", "407-341-5269"],
		"email": ["E-Mail:", "jonellcolon@aol.com"],
		"cpart": ["Car Part:", "Rotor"],
		"hmany": ["How Many:", "2"],
		"ctype": ["Car Type:", "Honda"],
		"cmodel": ["Car Model:", "Civic"],
		"ycar": ["Car Year:", "2001"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "Leave On"]
	
	},
	"part2": {
		"groups": ["Group:", "Cabin"],
		"fullname": ["Full Name:", "Rose Ayala"],
		"phone": ["Phone:", "407-437-7526"],
		"email": ["E-Mail:", "roseayala.colon@gmail.com"],
		"cpart": ["Car Part:", "Seats"],
		"hmany": ["How Many:", "4"],
		"ctype": ["Car Type:", "Toyota"],
		"cmodel": ["Car Model:", "Sienna"],
		"ycar": ["Car Year:", "2003"],
		"mode": ["Value:", "Used"],
		"special": ["Special Request:", "Do not lend."]
	},
	"part3": {
		"groups": ["Group:", "Wheels"],
		"fullname": ["Full Name:", "Eliana Colon"],
		"phone": ["Phone:", "407-249-0896"],
		"email": ["E-Mail:", "eli@newbirthorlando.org"],
		"cpart": ["Car Part:", "Hub Caps"],
		"hmany": ["How Many:", "2"],
		"ctype": ["Car Type:", "Ford"],
		"cmodel": ["Car Model:", "F-150"],
		"ycar": ["Car Year:", "1998"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "Save old."]
	},
	"part4": {
		"groups": ["Group:", "Trunk"],
		"fullname": ["Full Name:", "Isabella"],
		"phone": ["Phone:", "407-345-0700"],
		"email": ["E-Mail:", "isa@newbirthorlando.org"],
		"cpart": ["Car Part:", "Alignment"],
		"hmany": ["How Many:", "4"],
		"ctype": ["Car Type:", "Toyota"],
		"cmodel": ["Car Model:", "Corolla"],
		"ycar": ["Car Year:", "1997"],
		"mode": ["Value:", "Used"],
		"special": ["Special Request:", "Make sure is right."]
	},
	"part5": {
		"groups": ["Group:", "Exhaust"],
		"fullname": ["Full Name:", "Daisy Fuentes"],
		"phone": ["Phone:", "787-343-2913"],
		"email": ["E-Mail:", "daisy@aol.com"],
		"cpart": ["Car Part:", "Muffler"],
		"hmany": ["How Many:", "1"],
		"ctype": ["Car Type:", "Ford"],
		"cmodel": ["Car Model:", "Escort"],
		"ycar": ["Car Year:", "2003"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "Check on no holes."]
	},
	"part6": {
		"groups": ["Group:", "Body"],
		"fullname": ["Full Name:", "Yae Colon"],
		"phone": ["Phone:", "321-230-4245"],
		"email": ["E-Mail:", "ycolon@yahoo.com"],
		"cpart": ["Car Part:", "Red Paint"],
		"hmany": ["How Many:", "6"],
		"ctype": ["Car Type:", "Kia"],
		"cmodel": ["Car Model:", "Sephia"],
		"ycar": ["Car Year:", "2009"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "Matching colors."]
	},
	"part7": {
		"groups": ["Group:", "Engine"],
		"fullname": ["Full Name:", "Lisa Colon"],
		"phone": ["Phone:", "407-430-1432"],
		"email": ["E-Mail:", "lcolon@aol.com"],
		"cpart": ["Car Part:", "Timing Belt"],
		"hmany": ["How Many:", "1"],
		"ctype": ["Car Type:", "Saturn"],
		"cmodel": ["Car Model:", "Mantra"],
		"ycar": ["Car Year:", "2001"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "Save old one."]
	
	},
	"part8": {
		"groups": ["Group:", "Cabin"],
		"fullname": ["Full Name:", "Jennifer Ayala"],
		"phone": ["Phone:", "407-254-8790"],
		"email": ["E-Mail:", "jayala@gmail.com"],
		"cpart": ["Car Part:", "Floors"],
		"hmany": ["How Many:", "2"],
		"ctype": ["Car Type:", "Ford"],
		"cmodel": ["Car Model:", "Fusion"],
		"ycar": ["Car Year:", "2011"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "Rip old one out."]
	},
	"part9": {
		"groups": ["Group:", "Wheels"],
		"fullname": ["Full Name:", "Luz Colon"],
		"phone": ["Phone:", "407-506-1270"],
		"email": ["E-Mail:", "lncgo@hotmail.com"],
		"cpart": ["Car Part:", "Rims"],
		"hmany": ["How Many:", "4"],
		"ctype": ["Car Type:", "Jeep"],
		"cmodel": ["Car Model:", "Wrangler"],
		"ycar": ["Car Year:", "1993"],
		"mode": ["Value:", "Used"],
		"special": ["Special Request:", "Try to get new ones."]
	},
	"par10": {
		"groups": ["Group:", "Trunk"],
		"fullname": ["Full Name:", "Odalys Summerville"],
		"phone": ["Phone:", "407-581-6123"],
		"email": ["E-Mail:", "odalys@newbirthorlando.org"],
		"cpart": ["Car Part:", "Carpet"],
		"hmany": ["How Many:", "1"],
		"ctype": ["Car Type:", "Chevy"],
		"cmodel": ["Car Model:", "Impala"],
		"ycar": ["Car Year:", "2000"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "Change the old to new."]
	},
	"part11": {
		"groups": ["Group:", "Exhaust"],
		"fullname": ["Full Name:", "Lylis Colon"],
		"phone": ["Phone:", "407-256-4584"],
		"email": ["E-Mail:", "lyliscolon@gmail.com"],
		"cpart": ["Car Part:", "Manifold"],
		"hmany": ["How Many:", "1"],
		"ctype": ["Car Type:", "Honda"],
		"cmodel": ["Car Model:", "Hatchback"],
		"ycar": ["Car Year:", "1994"],
		"mode": ["Value:", "Used"],
		"special": ["Special Request:", "Old ones needs to be rebuilt."]
	
	},
	"part12": {
		"groups": ["Group:", "Body"],
		"fullname": ["Full Name:", "Elizabeth Sanchez"],
		"phone": ["Phone:", "407-596-4325"],
		"email": ["E-Mail:", "esanchez@hotmail.com"],
		"cpart": ["Car Part:", "Clear Coat"],
		"hmany": ["How Many:", "1"],
		"ctype": ["Car Type:", "Toyota"],
		"cmodel": ["Car Model:", "Tiburon"],
		"ycar": ["Car Year:", "2012"],
		"mode": ["Value:", "Used"],
		"special": ["Special Request:", "Careful with inner paint."]
	},
	"part13": {
		"groups": ["Group:", "Engine"],
		"fullname": ["Full Name:", "Jose Colon"],
		"phone": ["Phone:", "407-209-4587"],
		"email": ["E-Mail:", "jcolon@facebook.com"],
		"cpart": ["Car Part:", "Filter"],
		"hmany": ["How Many:", "1"],
		"ctype": ["Car Type:", "Ford"],
		"cmodel": ["Car Model:", "Elantra"],
		"ycar": ["Car Year:", "1991"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "Make sure old one is dirty."]
	},
	"part14": {
		"groups": ["Group:", "Cabin"],
		"fullname": ["Full Name:", "Aye Colon"],
		"phone": ["Phone:", "321-756-8979"],
		"email": ["E-Mail:", "aye@yahoo.com"],
		"cpart": ["Car Part:", "Back Seats"],
		"hmany": ["How Many:", "1"],
		"ctype": ["Car Type:", "Honda"],
		"cmodel": ["Car Model:", "Via"],
		"ycar": ["Car Year:", "1992"],
		"mode": ["Value:", "Used"],
		"special": ["Special Request:", "Needs to be remade."]
	},
	"part15": {
		"groups": ["Group:", "Wheels"],
		"fullname": ["Full Name:", "Rose Ayala"],
		"phone": ["Phone:", "407-242-3422"],
		"email": ["E-Mail:", "rayala@gmail.com"],
		"cpart": ["Car Part:", "Left Back Wheel"],
		"hmany": ["How Many:", "1"],
		"ctype": ["Car Type:", "Kia"],
		"cmodel": ["Car Model:", "Sanford"],
		"ycar": ["Car Year:", "2012"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "Change it do not fix."]
	},
	"part16": {
		"groups": ["Group:", "Trunk"],
		"fullname": ["Full Name:", "Isaac Mejia"],
		"phone": ["Phone:", "407-231-4431"],
		"email": ["E-Mail:", "imejia@gmail.com"],
		"cpart": ["Car Part:", "Space"],
		"hmany": ["How Many:", "1"],
		"ctype": ["Car Type:", "Jeep"],
		"cmodel": ["Car Model:", "Cherokee"],
		"ycar": ["Car Year:", "1999"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "Check on space for trunk."]
	},
	"par17": {
		"groups": ["Group:", "Exhaust"],
		"fullname": ["Full Name:", "Ray Santana"],
		"phone": ["Phone:", "407-240-0007"],
		"email": ["E-Mail:", "rayreyes@hotmail.com"],
		"cpart": ["Car Part:", "Filter"],
		"hmany": ["How Many:", "1"],
		"ctype": ["Car Type:", "Nissan"],
		"cmodel": ["Car Model:", "Quest"],
		"ycar": ["Car Year:", "1998"],
		"mode": ["Value:", "Used"],
		"special": ["Special Request:", "Save old."]
	},
	"part18": {
		"groups": ["Group:", "Body"],
		"fullname": ["Full Name:", "Justin Chapman"],
		"phone": ["Phone:", "787-234-5488"],
		"email": ["E-Mail:", "jchapman@aol.com"],
		"cpart": ["Car Part:", "Blue Paint"],
		"hmany": ["How Many:", "3"],
		"ctype": ["Car Type:", "Mazda"],
		"cmodel": ["Car Model:", "RX-7"],
		"ycar": ["Car Year:", "2010"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "2 shades of blue."]
	
	},
	"part19": {
		"groups": ["Group:", "Cabin"],
		"fullname": ["Full Name:", "Lou Fernandez"],
		"phone": ["Phone:", "407-213-2343"],
		"email": ["E-Mail:", "lou931@gmail.com"],
		"cpart": ["Car Part:", "Covers"],
		"hmany": ["How Many:", "2"],
		"ctype": ["Car Type:", "Nissan"],
		"cmodel": ["Car Model:", "Elantra"],
		"ycar": ["Car Year:", "2003"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "Get green ones with stripes."]
	},
	"part20": {
		"groups": ["Group:", "Engine"],
		"fullname": ["Full Name:", "Gabby Mejia"],
		"phone": ["Phone:", "407-345-1105"],
		"email": ["E-Mail:", "gabbymejia@yahoo.com"],
		"cpart": ["Car Part:", "Oil"],
		"hmany": ["How Many:", "2"],
		"ctype": ["Car Type:", "Honda"],
		"cmodel": ["Car Model:", "Civic"],
		"ycar": ["Car Year:", "2003"],
		"mode": ["Value:", "New"],
		"special": ["Special Request:", "Make sure no leaks."]
	}
		
}
	